name: Build kernel

on:
  push:
    branches: [ "tobacco" ]

jobs:
  build1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build kernel
      id: build
      # You may pin to the exact commit or the version.
     # uses: ianchb/android-kernel-actions-modif1@f80b7475fb4cdbcfee9dc1a5c5ccdf90760d4d80
      uses: ianchb/android-kernel-actions-modif1@02
      with:
        # Device architecture
        arch: arm64
        # Compiler to use
        compiler: clang/11/binutils
        # Defconfig to use
        defconfig: renoir-qgki_defconfig
       # Kernel image name
        image: Image
        
    - name: Archive files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r out.zip ${{ steps.build.outputs.outdir }}
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: out.zip
        path: './out.zip'    
        
  build2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build kernel
      id: build
      # You may pin to the exact commit or the version.
     # uses: ianchb/android-kernel-actions-modif1@f80b7475fb4cdbcfee9dc1a5c5ccdf90760d4d80
      uses: ianchb/android-kernel-actions-modif1@02
      with:
        # Device architecture
        arch: arm64
        # Compiler to use
        compiler: proton-clang/master
        # Defconfig to use
        defconfig: stock_defconfig
       # Kernel image name
        image: Image
        
    - name: Archive files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r out2.zip ${{ steps.build.outputs.outdir }}
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: out2.zip
        path: './out2.zip'
