name: Build kernel

on:
  push:
    branches: [ "tobacco" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Android Kernel Action with XZ
      id: build
      # You may pin to the exact commit or the version.
     # uses: ianchb/android-kernel-actions-modif1@f80b7475fb4cdbcfee9dc1a5c5ccdf90760d4d80
      uses: ianchb/android-kernel-actions-modif1@01
      with:
        # Device architecture
        arch: arm64
        # Compiler to use
        compiler: clang/11
        # Defconfig to use
        defconfig: renoir-qgki_defconfig
       # Kernel image name
        image: Image.gz-dtb
        
    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
